table grass_vs_trees
	lineageTag: ab6302d7-49ea-4f45-8e8e-c9faf2562f60

	column year
		dataType: int64
		formatString: 0
		lineageTag: 558adb58-6fc9-4468-bc95-b020904673aa
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column grass
		dataType: double
		lineageTag: bc693649-fc35-4354-89ea-d710cb5f0657
		summarizeBy: sum
		sourceColumn: grass

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trees_raw
		dataType: double
		lineageTag: bc5f8cd3-8912-4646-9eaa-b5dcb8a53c1e
		summarizeBy: sum
		sourceColumn: trees_raw

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trees_ground_removed
		dataType: double
		lineageTag: e212b5b6-5f53-4811-9bbc-fb98761e285b
		summarizeBy: sum
		sourceColumn: trees_ground_removed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition grass_vs_trees = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "grass_vs_trees.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"year", Int64.Type}, {"grass", type number}, {"trees_raw", type number}, {"trees_ground_removed", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

